### ISSUE TITLE
Не билдится (version 1.1.11)

### ISSUE THREAD

**Issue by ios-berizaryad** [cloudpayments/CloudPayments-SDK-iOS#12]
Версия 1.1.11 не билдится под iOS 12.0, на более новых ОС такая же проблема
Так же хотелось бы вас попросить рассмотреть возможность отказаться от добавления дополнительных зависимостей, в частности SnapKit и PromiceKit. Они заметно увеличивают вес билда.

Лог ошибок прилагаю

`Failed to build module 'YandexPaySDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)', while this compiler is 'Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)'). Please select a toolchain which matches the SDK.`

`Failed to build module 'XPlatPaySDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)', while this compiler is 'Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)'). Please select a toolchain which matches the SDK.`

**Comment by ivanstarchenkov** [comment]
same issue

**Comment by SalaarFiend** [comment]
same issue

**Comment by ign4** [comment]
Попробуйте версию 1.1.12

**Comment by Anton-1408** [comment]
@ign4 для версии 1.1.12 актуальная проблема

**Comment by ign4** [comment]
@Anton-1408 создал два пустых проекта в одном подключил так:
pod 'Cloudpayments', :git =>  "https://github.com/cloudpayments/CloudPayments-SDK-iOS", :branch => "master"

В другом так:
pod 'Cloudpayments', :git =>  "https://github.com/cloudpayments/CloudPayments-SDK-iOS", :tag => "1.1.12"

В обоих случаях все успешно подключилось и проект собрался, попробуйте удалить зависимости, а потом снова их добавить, возможно поможет clean build folder и тп.

**Comment by Anton-1408** [comment]
@ign4 Пробовал раннее - не помогло. Mackbook на m1pro , xcode Version 13.4.1 (13F100)

**Comment by rifmj** [comment]
@ign4 здравствуйте! Для версия 1.1.14 проблема все так же актуальна, приходится использовать версию 1.1.6

XCode Version 13.2.1 (13C100)
macOS Monterey Version 12.2 (21D49)
2,3 GHz 8-Core Intel Core i9

`Xcode/DerivedData/ProjectName-fbbfmxrxivdytjdulvhyoaowbcmy/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/XPlatPaySDK/XPlatPaySDK.framework/Modules/XPlatPaySDK.swiftmodule/arm64-apple-ios.swiftinterface:6:8: Cannot load underlying module for 'PromiseKit'`
 
`Xcode/DerivedData/ProjectName-fbbfmxrxivdytjdulvhyoaowbcmy/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/YandexPaySDK/YandexPaySDK.framework/Modules/YandexPaySDK.swiftmodule/arm64-apple-ios.swiftinterface:10:8: Failed to build module 'XPlatPaySDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)', while this compiler is 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)'). Please select a toolchain which matches the SDK.`

**Comment by ign4** [comment]
@Anton-1408 @rifmj Приложение нативное или используется что-то кросс платформенное типа react-native?

**Comment by ivanstarchenkov** [comment]
Все еще не собирается, полагаю, что проблема в кривой интеграции с какао подс, уже давно нужно было добавить сдк в их каталог

**Comment by ivanstarchenkov** [comment]
<img width="725" alt="Screen Shot 2022-09-14 at 8 22 15 PM" src="https://user-images.githubusercontent.com/106306025/190221246-db292b85-9e05-42f9-ab8a-d5b3b08cbd76.png">

**Comment by ivanstarchenkov** [comment]
Macbook M1, xcode 14, ios 16.0, нативный swift код
