### ISSUE TITLE
XCode 14

### ISSUE THREAD

**Issue by k0derAl** [cloudpayments/CloudPayments-SDK-iOS#13]
Hello 

Can you fix compile error for  XCode 14?

**Comment by k0derAl** [comment]
Value of optional type '[String : Any]?' must be unwrapped to refer to member 'subscript' of wrapped base type '[String : Any]'

'keyboardWillShowNotification' has been renamed to 'NSNotification.Name.UIKeyboardWillShow'

'keyboardFrameEndUserInfoKey' has been renamed to 'UIKeyboardFrameEndUserInfoKey'

**Comment by ign4** [comment]
Please update SDK version to 1.2.1
