### ISSUE TITLE
Чистый URLSession без Alamofire

### ISSUE THREAD

**Issue by MihaelIsaev** [cloudpayments/CloudPayments-SDK-iOS#6]
Привет!

Мы в нашем проекте сейчас используем CodyFire которая базируется на Alamofire 4 и как я понимаю CloudPayments использует Alamofire 5. В результате cocoapods ни на что не ругается (потому что в вашем podspec явно версия Alamofire не указана), но SDK CloudPayments не компилируется явно из-за того, что установлен Alamofire 4.

CodyFire наша разработка, мы сами планируем выпилить Alamofire за ненадобностью и всегда хорошо выбросить лишнюю зависимость.
В данный момент пока не знаем что делать, возможно быстро перепишем CodyFire без Alamofire, чтобы не блочить разработку т.к. интеграция платежки это последнее, что осталось перед релизом нашего приложения.

Мы и вам желаем от Alamofire избавиться как можно скорее 🙂

**Comment by ign4** [comment]
Добрый день! К сожалению сейчас убрать Alamofire в разумные сроки мы не сможем, изменение версии Alamofire на более позднюю потенциально может вызвать проблемы с компиляцией у других клиентов.

**Comment by MihaelIsaev** [comment]
Жаль, что вы изначально не сделали SDK чистым от зависимостей в угоду минимальным удобствам при написании кода. Сейчас мы проводим большую работу, чтобы мучиться с вашим SDK. Спасибо!
