### ISSUE TITLE
Отправка email с встроенной формой

### ISSUE THREAD

**Issue by Liptor** [cloudpayments/CloudPayments-SDK-iOS#8]
Провожу интеграцию в ios приложение и стоит задача отправки email пользователя во время передачи данных PaymentData. Передача вместе с jsonData не отображает email в админке, таким образом стоит вопрос, как можно отправить email пользователя вместе с PaymentData? Интеграция проводится со стандартной формой. Видел возможность передачи email со своей формой, но там нужна криптограмма. Есть ли возможность передавать email со стандартной формой без использования криптограммы?

**Comment by ign4** [comment]
Через JsonData емайл не передается, для этого есть специальное поле email, в него можно передать емайл когда вы используете свою форму, а на стандартной форме ввода карточных данных есть поле для ввода емайл пользователем, это введенный email и передается в это поле.
