### ISSUE TITLE
bundleID error unwrapping optional value

### ISSUE THREAD

**Issue by ycdehan** [cloudpayments/CloudPayments-SDK-iOS#9]
orderID = 123

let paymentData = PaymentData.init(publicId: "...")
            .setAmount("1")
            .setCurrency(.ruble)
            .setAccountId("111")
            .setInvoiceId("\(orderId)")
        
        let configuration = PaymentConfiguration.init(
            paymentData: paymentData,
            delegate: self,
            uiDelegate: self,
            scanner: nil,
            useDualMessagePayment: true,
            disableApplePay: true
        )

        PaymentForm.present(with: configuration, from: self)

после запуска кода, получаем эксепшн:

CloudpaymentsSDK/Bundle+Extenstions.swift:15: Fatal error: Unexpectedly found nil while unwrapping an Optional value
2022-04-08 20:57:51.540116+0500 papoose[34497:4851643] CloudpaymentsSDK/Bundle+Extenstions.swift:15: Fatal error: Unexpectedly found nil while unwrapping an Optional value

import Foundation

extension Bundle {
    class var mainSdk: Bundle {
        let bundle = Bundle.init(for: PaymentForm.self)
        let bundleUrl = bundle.url(forResource: "Cloudpayments", withExtension: "bundle")
        return Bundle.init(url: bundleUrl!)!  -------> вот на этой строке, ругается на bundleUrl!
    }
}

**Comment by NikitaLobanov** [comment]
такую ошибку можно встретить, если использовать SPM, через CocoaPods ошибка не возникает

**Comment by ign4** [comment]
Уточните ошибка через CocoaPods или через SPM?

**Comment by ArmyXomuiL** [comment]
У нас тоже такая ошибка через SPM
